# Generated by Django 2.1.3 on 2018-11-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Marca',
        ),
    ]
