# Generated by Django 2.1.3 on 2018-11-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20181109_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Anno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='Color',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='Modelo',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='NumPuertas',
            field=models.IntegerField(default=0),
        ),
    ]
