# Generated by Django 2.1.3 on 2018-11-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20181109_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='Color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='Modelo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
