# Generated by Django 2.1.3 on 2018-11-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_auto_20181109_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Descripción',
        ),
    ]
