# Generated by Django 2.1.3 on 2018-11-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_auto_20181109_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Imagen',
            field=models.ImageField(default='', upload_to='photos'),
        ),
    ]
