# Generated by Django 2.1.3 on 2018-11-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
