# Generated by Django 2.1.3 on 2018-11-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_auto_20181109_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Imagen',
        ),
    ]
